### ISSUE TITLE
prime notation is wrong

### ISSUE THREAD

**Issue by BlackCapCoder** [antimatter-dimensions/notations#10]
https://github.com/antimatter-dimensions/notations/blob/ca22e028f62fb5616d13b0bc920e9d52106724de/src/prime.ts#L59-L63

First, this is wrong- it will produce "factorizations" that are not equal to the original number. Second, 10k is ridiculously low! You hardly ever see numbers that low in antimatter dimension.

I realize that this is intended to be a shorthand, so 10007 is written "(2²×5²)^(2)" in prime notation for the same reason that it is written "1.00e4" in scientific. I also realize that integer factorization is in NP and that you have to cut corners at some point in favor of gameplay.

However, incorrect factorizations that doesn't even share any factors with the original number is borderline offensive! Can we do better?

**Comment by Ikerstreamer** [comment]
When I designed this system it wasn't meant to be taken seriously, It was an interesting way of displaying numbers which were unique from the styles of the other notations.

- If you go much larger with the number used before breaking into the next layer it causes major performance issues.
- It has the same level of precision as say scientific notation, and I don't see anyone complaining about that notation.
- When a number gets larger than 9,007,199,254,740,991 (~9e15 - Scientific notation) in js the computer no longer keeps track of the entire number, thus it would be impossible to factorize numbers greater than that perfectly. Therefore I don't see a reason as to why one would need perfect factorization.
- The expression would get unreasonably long making it hard to quickly compare numbers. The usage of exponentially layered factorization system makes it easy to compare the magnitudes of different number without having to look at the entire number. The whole number can, however, be used still to compare smaller changes.
 
However, if you have any ideas on how to make it better feel free to suggest. I do not plan on remaking this unless someone comes up with a better way which does not cause performance issues. The format function is called hundreds if not thousands of times per `gameLoop` iteration, so the execution should be kept extremely lightweight as it would be silly to have the notation formatting be a bottleneck in the performance of the game.

**Comment by BlackCapCoder** [comment]
Could we move the size restriction from the input number to its factors instead?

Regarding performance. In my experience, for small numbers (no factor greater than a billion) trail division is (almost always) the fastest algorithm. Pre-computing small primes as in the current implementation is useless- it is faster to just calculate them.

```javascript
// Naive trail division
function * factors (n, limit=10000)
{
  const lim = Math.min (limit, Math.floor (Math.sqrt(n)));

  for (let i = 2; i <= lim && i < n; i++)
    while (n % i == 0)
      yield i, n /= i; // We could recompute sqrt here, but sqrt is super slow so we don't want it in a loop

  yield n
}

// Slightly clever version
function * factors_ (n, limit=10000)
{
  for (let k of [2, 3])
    for (; n % k == 0; n /= k)
      yield k;

  const lim = Math.min (limit, Math.floor (Math.sqrt(n)));

  // All primes > 3 are of the form 6+-1
  for (let [a,b] = [5,4]; a <= lim && a < n; [a,b] = [b + 3, a + 3])
    for (; n % a == 0; n /= a) // Compilers are generally better at optimizing nested for loops
      yield a;

  yield n
}
```

I know about 2 cases where another algorithm beats trail division on small numbers:
* Fermat factorization if the input is semi-prime
* Prime testing if the input is prime

I can provide code for both, but I don't think they are applicable in our case since we only care about factors <10k.

**Comment by BlackCapCoder** [comment]
If we move the size restriction to factors then we get the problem that the notation could get lengthy. One solution is to limit the number of distinct factors to, say, 5, and then use scientific notation for the rest.

```
2*2*3*5*7*11*341509 = 1577771580 = 2^2*3*5*7*11*34.15e4
```

**Comment by dan-simon** [comment]
At roughly 9e15, as Iker said, computing the factorization of the input number itself becomes somewhat meaningless due to precision loss (JS has no int type, only an abused float type). However, up to 9e15, getting all factors less than 10000 with BlackCapCoder's slightly clever version of trial division isn't that bad: on Chrome, ```t0 = Date.now(); for (let i = 0; i < 1000; i++) {for (let i of factors_(Math.floor(Math.random() * 1e15))) {}}; t1 = Date.now()``` (factorizing 1000 numbers) took ~50ms, and even on Safari, it took only ~250ms. Notation length also shouldn't be an issue; I think (though I haven't tested) that if we don't factor any numbers over 9e15, prime notation will express numbers as less than 40 characters long 99% of the time, comparable to standard notation, roman notation, and imperial notation (though it might be harder than it is now to compare two numbers in prime notation). So doing trial division for all factors less than some size (maybe 1e4) seems reasonable, with or without scientific formatting of the unfactorized part (formatting the unfractorized part is basically irrelevant for efficiency and shortens worst-case length).

As for what happens above 9e15, I don't see any way factorization could be made anything but misleading (other than creating an int type, which would be inefficient in most incremental game situations), and I also don't immediately see any better option than the current system of rounding and including exponents. The 1e4 threshold for including exponents seems changeable without too much work (except for the explicit list of primes), so changing the threshold to 1e12 or 9e15, plus changing the factorization to factor-size-limited trial division, seems like it's the best that can be done.

I think I'm going to make a PR in a new branch of my fork with the slightly clever version of trial division (perhaps slightly modified) and a Number.MAX_INT threshold; I don't know if it will be accepted, but it will presumably provide an easier way to run tests. I'm unsure what effect the compilation from Typescript will have on code speed.

**Comment by BlackCapCoder** [comment]
@dan-simon If javascript treat integers as floats, it would imply that it uses the VEX registers and VEX operations in x86, do you happen to know if that is the case? If so it would be beneficial to unroll the loop a bit so each iteration does several passes.

**Comment by dan-simon** [comment]
Unfortunately I know basically nothing about anything low-level, especially in practice, so I have no idea whether Javascript uses the VEX registers and VEX operations (although if they are the only or the fastest way to do float operations, I assume they are used at least sometimes). I do know that most modern JavaScript engines use just-in-time compilation and are often optimized very extensively, so, to my limited understanding, after a function (such as the factorization function) is called enough with an integer parameter, it might be optimized to first check that its inputs are integers and then run assembly code that only works with integers.

In any case, the other parts of prime notation appear to take basically no time compared to the factorization function, and 1e4 seems like a high enough limit on factors (if we could raise it to 1e8 and do full factorization, that would be nice, but that seems completely impractical), so I think whether further optimization is needed depends on how many numbers this library needs to format per second, which is in practice how many numbers Antimatter Dimensions formats per second. Apparently right now prime notation can format about 4000 numbers per second even in Safari on my several-year-old Mac, which I think might be enough given that Antimatter Dimensions updates the screen at most 30 times per second and generally only displays a few dozen numbers at once. @Razenpok Do you have any idea how many numbers formatted per second AD requires at worst and/or what fraction of the time formatting can take up?

**Comment by BlackCapCoder** [comment]
This is about 20% faster on my machine. Optimizing javascript is weird.

```javascript
for (let a = 5; a <= lim && a < n;) {
  for (; n % a == 0; n /= a) yield a; a += 2;
  for (; n % a == 0; n /= a) yield a; a += 4;
}
```

------

```javascript
for (let [a,b] = [5,4]; a <= lim && a < n; [a,b] = [b + 3, a + 3])
  for (; n % a == 0; n /= a)
    yield a;
// ~50ms

for (let a = 5; a <= lim && a < n;) {
  for (; n % a == 0; n /= a) yield a; a += 2;
  for (; n % a == 0; n /= a) yield a; a += 4;
}
// ~40ms

for (let a = 5, b = 7; a <= lim && a < n;) {
  for (; n % a == 0; n /= a) yield a; a += 6;
  for (; n % b == 0; n /= b) yield b; b += 6;
}
// ~45ms

for (let a = 5, b = 7, c = 11; a <= lim && a < n;) {
  for (; n % a == 0; n /= a) yield a; a += 6;
  for (; n % b == 0; n /= b) yield b; b += 6;
  for (; n % c == 0; n /= c) yield c; c += 6;
}
// ~70ms

for (let a = 5, b = 7, c = 11, d = 13; a <= lim && a < n;) {
  for (; n % a == 0; n /= a) yield a; a += 6;
  for (; n % b == 0; n /= b) yield b; b += 6;
  for (; n % c == 0; n /= c) yield c; c += 6;
  for (; n % d == 0; n /= d) yield d; d += 6;
}
// ~80ms
```

**Comment by BlackCapCoder** [comment]
And this is 10 times faster than the last one!

It is a bit fragile, so be careful about changing anything. If you use `while (true)` instead of `while (false)` for instance it runs in 40ms instead of 4.

```javascript
let a = 5, b = 4, r = 0;

do {
  r = n % a;
  n = Math.floor(n / a);

  if (r == 0)
  {
    yield a;
    continue;
  }

  n *= a;
  n += r;
  r  = 0;
  a += 3;
  b += 3;

  {
    const tmp = a;
    a = b;
    b = tmp;
  }

  if (a <= lim && a < n)
    continue;

} while (false);
```

The way I came up with this is that I first wrote it down in psuedo-assembly, then translated that to javascript. I figured that since unrolling made it slower it is probably using integer instructions.
```assembly
#define n eax
#define r edx

a = 5
b = 4
r = 0

factor:
  div n, a ; n=n/a, r=n%a

  mov r, r ; sets ZF
  jz factor

  n *= a
  n += r
  r  = 0

  a += 3
  b += 3
  xchg a, b

  cmp a, limit
  jge factor
```

**Comment by dan-simon** [comment]
The partial unrolling to remove `b` looks good. It seems to give me a ~25% speedup on Chrome, and a ~10% speedup on Safari.

I tried defining a function that runs the code you made from pseudo-assembly and input 77 to the function, and it didn't yield anything. I think that might be because in a Javascript `do {} while (false)` loop, `continue` just exits the loop (for example, `i = 0; do {i++; continue} while (false); console.log(i)` terminates almost immediately and logs 1). However, it's also likely I did something wrong in putting the code in a function, though I'm not sure what.

The exact code I ran was:
```
lim = 1e4;

function * f(n) {
let a = 5, b = 4, r = 0;

do {
  r = n % a;
  n = Math.floor(n / a);

  if (r == 0)
  {
    yield a;
    continue;
  }

  n *= a;
  n += r;
  r  = 0;
  a += 3;
  b += 3;

  {
    const tmp = a;
    a = b;
    b = tmp;
  }

  if (a <= lim && a < n)
    continue;

} while (false);
}

console.log(Array.from(f(77)))
```
and it logged `[]`.

**Comment by BlackCapCoder** [comment]
@dan-simon I assumed that continue in `while (false)` would restart the loop, so the implementation is wrong. Back the the drawing board.

The theoretical lowerbound is about 6 clocks per loop cycle which is a worst case scenario of about 1ms in our benchmark on a 2gz processor.

**Comment by BlackCapCoder** [comment]
`~20ms`. The do loop is very slightly faster than the for loop. The actual speed gain comes from the first line, which is a nop.

```javascript
function * factors (n, limit=10000)
{
  n >>= 0; // Forces n to be an integer, 100% speed gain

  for (let k = 2; k != 4; ++k)
    for (; n % k == 0; n /= k)
      yield k;

  n >>= 0; // Still integer! (Not sure if this helps)

  const lim = Math.min (limit, Math.floor (Math.sqrt(n)));
  let a = 5, i = 4;

  do {
    const r = !(n % a);

    if (r)
    {
      n /= a;
      yield a;
    }

    a += i ^= 6;

  } while (a <= lim)

  yield n;
}
```

**Comment by Ikerstreamer** [comment]
I am happy if you guys want to update the notation just wanted to let you know that I have my reasons for not wanting to do it.

**Comment by Ikerstreamer** [comment]
@dan-simon I can get you some numbers on how often the format code is run.

**Comment by BlackCapCoder** [comment]
`~20ms`. This only works when `limit <= 2^31-1`

edit: this is incorrect- don't use it for now

```javascript
function * factors (_n, limit=10000)
{
  // Bitwise operators cast the number to a 32-bit signed integer,
  // which is faster than floats.
  // We don't want negative numbers, so we don't include the sign bit.
  const mask = 0x7fffffff;
  let n      = _n & mask;

  for (; !(n % 2); n /= 2) yield 2;
  for (; !(n % 3); n /= 3) yield 3;

  const lim = Math.min (limit, Math.sqrt(n)) >> 0;

  for (let a = 5; a <= lim && a < n;) {
    for (; !(n % a); n /= a) yield a; a += 2;
    for (; !(n % a); n /= a) yield a; a += 4;
  }

  // We still want to support numbers > 31-bits though
  yield _n > mask ? _n / (_n & mask / n) : n;
}
```

**Comment by dan-simon** [comment]
A new community notation which is a more precise version of Prime has been added. This notation right now isn't planned to be in the game but if enough people want to replace Prime by it or more generally think Prime isn't precise/accurate enough it probably will be. Closing because it seems very unlikely that Prime will become more accurate in the next few months and Prime's inaccuracy isn't a severe bug (any version of Prime has to be inaccurate somehow or use something like Shor's algorithm).
