### ISSUE TITLE
Once we get community notations, create a different section for those compared to those in game.

### ISSUE THREAD

**Issue by earthernsence** [antimatter-dimensions/notations#22]
You could either keep it centered and have a header for community ones, or you could separate them into different columns.

**Comment by dan-simon** [comment]
Just to check, is it the consensus that community notations won't be added to the game? Assuming  the game is going to use this library, it'll load any community notations added to this library anyway.

**Comment by earthernsence** [comment]
> Just to check, is it the consensus that community notations won't be added to the game? Assuming the game is going to use this library, it'll load any community notations added to this library anyway.

I believe so.

**Comment by dan-simon** [comment]
~~Ok so I can add make PRs for my cringey notation ideas without needing to die from embarrassment due to people actually seeing the notations in practice, good to know~~

More seriously, it would be cool if importing a community notation name would switch the game to that notation, like with secret themes. Of course, if there's some way to stop the community notations from even being loaded (like an alternate light version of the library without the community notations, or AD not actually using the library), then importing the community notations is probably a bad idea due to increased load time. Also, maybe importing notations is difficult or impossible to code for some reason.
