### ISSUE TITLE
Imperial ends before e9e15

### ISSUE THREAD

**Issue by realrapidjazz** [antimatter-dimensions/notations#4]
Currently, imperial doesn’t display values correctly past a certain point (around 1e6.7e11). Hence, some adjectives need to be added.

Suggestions: 

‘Microscopic’ - before minute
‘Meager’ - between small and modest
‘Abundant’ - between large and great
‘Expansive’ - between large and great (after abundant?)
‘Grand’ - between great and huge
‘Immense’ - between gigantic and colossal
‘Endless’ - after cosmic

**Comment by earthernsence** [comment]
either before or after cosmic, 'Galactic', after endless, 'Infinite', and after Infinite, 'Eternal'

**Comment by dan-simon** [comment]
For reference, I think we need 5 new units to get up to 1e9e15.

**Comment by James103** [comment]
The exact current cutoff point is at `3.09066027102114015967e670266993468`.

**Comment by dan-simon** [comment]
This is now the last open issue, if someone can give me a list of five new units and where to put them I'll add them.

**Comment by dan-simon** [comment]
@realrapidjazz @garnet420 Do either of you have any thoughts on this? Razen suggested fixing this issue but getting feedback first on which units to add and where (as stated above, we need five more). If for some reason it's private we can talk via Discord DMs or something, but it seems fine to do this in public for me.

We have far more than five options for new units so this is probably mostly just picking and choosing.

**Comment by James103** [comment]
Instead of continuously adding new units, I think it may be a better idea to just do something similar to one of the following examples:
* "You have 1.23e4 **ghostly^2** unstable quarks." -> "12 **eternal^2** cosmic minims"
* "You have 1.23e4 **Mk3** infinity points." -> "12 **Mk3** cosmic ounces"
* "You have 1.23e4 **meta^4**-eternity points." -> "12 **meta^4**-cosmic quarts"

This would easily extend Imperial notation to e1.8e308 and beyond.

**Comment by dan-simon** [comment]
Firstly I should say that I like this idea (though I'm not sure which specific solution I like the most). However, the standard for notations in this library is that they go up to the limit of break_infinity.js (e9e15), which is the number library this notation library uses, and I think some notifications currently don't work beyond e9e15 and that's considered fine. So as a result, code that only runs for numbers greater than e9e15 is for practical purposes dead code. We could use a solution like the ones you suggest for the extra five units (after cosmic), but since in my opinion we have more than five good suggestions already that's sort of pointless.

At first sight, it seems plausible that it would be good for notations to work with break_eternity.js or other high number libraries too. But I think as of now break_eternity.js breaks some notations due to incompatibilities with break_infinity.js (and these incompatibilities would make it hard to make a notation that works with both), and I'm not sure there's an easy way to substitute break_eternity.js for break_infinity.js when loading notations anyway (my guess is no).

If I had infinite time then I'd probably want to make a version of this library that works with break_eternity.js with exactly the same notations (except for changes to make them work beyond e9e15), but I don't have infinite time so I probably won't make such a version (and I'm not sure if it's even a good idea; I'd probably want to ask various people before doing it).
